name: nwc_densetsu
description: Network diagnostic tool
version: 0.1.0
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.5.0
  file_selector: ^1.0.0
  
  # file_picker: ^6.1.1
  path: any
  http: ^1.4.0
  fl_chart: ^0.63.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 


