name: nwc_densetsu
description: Network diagnostic tool
version: 0.1.0
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_selector: ^1.0.0
  path: any
  http: ^1.4.0
  fl_chart: ^0.63.0
  flutter_svg: ^2.2.0
  xml: ^6.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 


